version: '3'

services:
  uptodo.hosts:
    build:
      context: .
      dockerfile: UpToDo.Hosts/Dockerfile
    image: uptodo.hosts
    container_name: uptodo.hosts
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - uptodo.postgres

  uptodo.postgres:
    image: postgres:15-alpine
    container_name: uptodo.postgres
    restart: always
    environment:
      POSTGRES_DB: uptodo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
